apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: redditrend-ingress
  namespace: redditrend
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
  - http:
      paths:
      - path: /api(/|$)(.*)
        pathType: Prefix
        backend:
          service:
            name: fastapi-service
            port:
              number: 80
      - path: /(.*)
        pathType: Prefix
        backend:
          service:
            name: react-app-service
            port:
              number: 80