apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-backend
  namespace: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fastapi-backend
  template:
    metadata:
      labels:
        app: fastapi-backend
    spec:
      containers:
        - name: fastapi-backend
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          image: fastapi-backend:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8000
          env:
            - name: CASSANDRA_HOST
              value: "cassandra-service"
            - name: CASSANDRA_PORT
              value: "9042"
            - name: USE_MOCK
              value: "true"
          command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
---
apiVersion: v1
kind: Service
metadata:
  name: fastapi-service
spec:
  selector:
    app: fastapi-backend
  ports:
    - protocol: TCP
      port: 80 #expose 80 but forward to 8000
      targetPort: 8000
  type: ClusterIP