apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-backend
  namespace: redditrend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fastapi-backend
  template:
    metadata:
      labels:
        app: fastapi-backend
    spec:
      containers:
        - name: fastapi-backend
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          image: aldobuzi/redditrend-repository:fastapi-backend
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
          env:
            - name: CASSANDRA_HOST
              value: "cassandra-service"
            - name: CASSANDRA_PORT
              value: "9042"
            - name: USE_MOCK
              value: "false"
          command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
---
apiVersion: v1
kind: Service
metadata:
  name: fastapi-service
  namespace: redditrend
spec:
  selector:
    app: fastapi-backend
  ports:
    - protocol: TCP
      port: 80      # service port inside cluster
      targetPort: 8000
      nodePort: 30080  # NodePort exposed on each node's IP (choose an unused port 30000-32767)
  type: NodePort