apiVersion: batch/v1
kind: Job
metadata:
  name: cassandra-init
spec:
  template:
    spec:
      containers:
      - name: cassandra-init
        image: cassandra:3.11
        command: ["sh", "-c"]
        args:
          - cqlsh cassandra-service < /schema/schema.cql
        volumeMounts:
        - name: schema-volume
          mountPath: /schema
      restartPolicy: OnFailure
      volumes:
      - name: schema-volume
        configMap:
          name: cassandra-schema