apiVersion: batch/v1
kind: Job
metadata:
  name: cassandra-init
  namespace: redditrend
spec:
  template:
    spec:
      containers:
      - name: cassandra-init
        image: cassandra:3.11
        command: ["sh", "-c"]
        args:
          - cqlsh cassandra-service < /schema/schema.cql #connect to cassandra-service and execute the schema file
        volumeMounts:
        - name: schema-volume
          mountPath: /schema # Mounts the ConfigMap (cassandra-schema) at /schema
      restartPolicy: OnFailure
      volumes:
      - name: schema-volume
        configMap:
          name: cassandra-schema