apiVersion: batch/v1
kind: CronJob
metadata:
  name: spark-moving-window
spec:
  schedule: "*/60 * * * *"  # every 60 minutes
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: spark
          restartPolicy: Never
          containers:
            - name: spark-moving-window
              image: aldobuzi/redditrend-repository:spark-moving-window
              imagePullPolicy: IfNotPresent
              command: 
                - /opt/bitnami/spark/bin/spark-submit
                - --master 
                - k8s://https://192.168.200.9:6443 #master node
                - --deploy-mode 
                - cluster
                - --conf
                - spark.kubernetes.container.image=aldobuzi/redditrend-repository:spark-moving-window
                - --conf # specify path for cache and other stuff as an absolute path
                - spark.jars.ivy=/tmp/.ivy2
                - --conf 
                - spark.kubernetes.namespace=redditrend
                - --conf
                - spark.kubernetes.authenticate.driver.serviceAccountName=spark
                - --conf 
                - spark.driver.memory=512m
                - --conf 
                - spark.driver.memoryOverhead=512m
                - --conf 
                - spark.executor.memory=512m
                - --conf 
                - spark.executor.instances=1
                - --name 
                - spark-moving-window 
                - --packages 
                - org.apache.spark:spark-sql-kafka-0-10_2.12:3.5.5,com.datastax.spark:spark-cassandra-connector_2.12:3.5.1
                - local:///opt/bitnami/spark/moving-window.py
              env:
                - name: SPARK_CASSANDRA_HOST
                  value: "cassandra-service"
                - name: SPARK_CASSANDRA_KEYSPACE
                  value: "graph"
          resources:
            requests:
              memory: "2Gi"
              cpu: "1"
            limits:
              memory: "2Gi"
              cpu: "2"